### ISSUE TITLE
lib mongoc error: No such file there

### ISSUE THREAD

**Issue by ghost** [datanoise/mongo.cr#16]
Maybe someone could help me with this, I installed everything but it is not working anyway.

Error:
```Bash
/home/daniel/.cache/crystal/crystal-run-database.tmp: error while loading shared libraries: libmongoc-1.0.so.0: cannot open shared object file: No such file or directory
```

**Comment by azzuwan** [comment]
@oltmannsdaniel  Did you managed to solve this issue? Why do you close this without an explanation?

**Comment by ghost** [comment]
Just forgot the `sudo ldconfig`.
