### ISSUE TITLE
Getting the _id of an inserted document

### ISSUE THREAD

**Issue by dbackeus** [datanoise/mongo.cr#4]
Since Collection#insert returns nil, any idea how to find out what _id mongodb auto-added to the new document?

**Comment by datanoise** [comment]
You need to use last_error method. I believe there is a comment to insert

**Comment by dbackeus** [comment]
Right you are :+1:

**Comment by codenoid** [comment]
i just got 

```
{ "nInserted" : 1, "nMatched" : 0, "nModified" : 0, "nRemoved" : 0, "nUpserted" : 0, "writeErrors" : [  ] }
``` 

from `.last_error` :( @datanoise
