### ISSUE TITLE
Is there any way to list all collection entries ?

### ISSUE THREAD

**Issue by waghanza** [datanoise/mongo.cr#8]
Hello,

I want to list all entries of my collection.

Is there any way to do this ?

Regards,

**Comment by waghanza** [comment]
I answer to myself, no
This is not available on C lib

**Comment by amiceli** [comment]
If it can help someone, you can do that : 

    tagCollection = db["tags"]
    tagCollection.find(BSON.new).each do |doc|
      puts doc
    end
